### DISCUSSION TITLE
Bash completion turns off filename completion

### DISCUSSION THREAD

**Discussion by dantheman3333** [pacak/bpaf#108] [General]
Hi, I'm having some troubles with the bash auto completion (ubuntu, standard terminal)

```bash
./target/debug/completion echo Ca
```
`press tab` ->
```bash
./target/debug/completion echo Cargo.
```

tab completion works here for the filename `Cargo.toml`

-----------------------------------------
After turning on autocomplete:
```bash
./target/debug/completion --bpaf-complete-style-bash >> ~/.bash_completion
```
and opening a new terminal:
`./target/debug/completion ec` correctly autocompletes to `./target/debug/completion echo`. Another tab produces `./target/debug/completion echo <FILE> ` which may not be ideal.

The issue occurs when pressing tab on `./target/debug/completion echo Car` which results in `./target/debug/completion echo Car ` , simply adding a space rather than completing the filename. 

---------------------------------------------
```rust
use bpaf::*;

use std::path::PathBuf;


#[derive(Clone, Debug)]
enum Opts {
    FileOptions { file_path: PathBuf },
}

fn args() -> Opts {
    let file_path = positional::<PathBuf>("FILE");
    let echo_cmd = construct!(Opts::FileOptions { file_path })
        .to_options()
        .command("echo");
    let parser = construct!([echo_cmd]);
    parser.to_options().run()
}

fn main() {
    let args = args();
    match args {
        Opts::FileOptions { file_path } => println!("{}", file_path.to_string_lossy())
    }
}
```
```toml
[package]
name = "completion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpaf = { version = "0.7.1", features = ["autocomplete"] }
```
